syntax = "proto3";

package linktracker.v1;

option go_package = "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/proto;linktrackerv1";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

message ChatRequest {
  int64 chat_id = 1;
}

message AddLinkRequest {
  int64 chat_id = 1;
  string url = 2;
  repeated string tags = 3;
}

message DeleteLinkRequest {
  int64 chat_id = 1;
  string url = 2;
}

message AddTagRequest {
  int64 chat_id = 1;
  string url = 2;
  string tag = 3;
}

message DeleteTagRequest {
  int64 chat_id = 1;
  string url = 2;
  string tag = 3;
}

message GetTagsRequest {
  int64 chat_id = 1;
  string url = 2;
}

message ListLinksRequest {
  int64 chat_id = 1;
  repeated string tags = 2;
}

message Link {
  string url = 1;
  repeated string tags = 2;
  google.protobuf.Timestamp last_update = 3;
}

message ListLinksResponse {
  repeated Link links = 1;
  int32 size = 2;
}

message GetTagsResponse {
  repeated string tags = 1;
  int32 size = 2;
}

service ScrapperService {
  rpc AddChat(ChatRequest) returns (google.protobuf.Empty);
  rpc DeleteChat(ChatRequest) returns (google.protobuf.Empty);
  rpc AddLink(AddLinkRequest) returns (google.protobuf.Empty);
  rpc DeleteLink(DeleteLinkRequest) returns (google.protobuf.Empty);
  rpc AddTag(AddTagRequest) returns (google.protobuf.Empty);
  rpc DeleteTag(DeleteTagRequest) returns (google.protobuf.Empty);
  rpc GetTags(GetTagsRequest) returns (GetTagsResponse);
  rpc ListLinks(ListLinksRequest) returns (ListLinksResponse);
}
